package com.eldritch.helpers.campaignmanagementservice.models

enum class Token {
    CLUE,
    GATE,
    ELDRITCH_TOKEN,
    MONSTER,
    FOCUS,
    RESOURCE,
    DOOM_TOKEN,
    OMEN_TOKEN,
    DEVASTATION
}

enum class TokenLocation(val expansion: Expansion) {
    OMEN_GREEN(Expansion.Core),
    OMEN_BLUE_1(Expansion.Core),
    OMEN_RED(Expansion.Core),
    OMEN_BLUE_2(Expansion.Core),
    DOOM_TRACK(Expansion.Core),
    DISCARD(Expansion.Core),
    CURRENT_MYSTERY(Expansion.Core),
    SAN_FRANSISCO(Expansion.Core),
    ARKHAM(Expansion.Core),
    BUENOS_AIRES(Expansion.Core),
    LONDON(Expansion.Core),
    ROME(Expansion.Core),
    ISTANBUL(Expansion.Core),
    TOKYO(Expansion.Core),
    SHANGHAI(Expansion.Core),
    SYDNEY(Expansion.Core),
    THE_AMAZON(Expansion.Core),
    THE_PYRAMIDS(Expansion.Core),
    THE_HEART_OF_AFRICA(Expansion.Core),
    ANTARCTICA(Expansion.Core),
    TUNGUSKA(Expansion.Core),
    THE_HIMALAYAS(Expansion.Core),
    SPACE_1(Expansion.Core),
    SPACE_2(Expansion.Core),
    SPACE_3(Expansion.Core),
    SPACE_4(Expansion.Core),
    SPACE_5(Expansion.Core),
    SPACE_6(Expansion.Core),
    SPACE_7(Expansion.Core),
    SPACE_8(Expansion.Core),
    SPACE_9(Expansion.Core),
    SPACE_10(Expansion.Core),
    SPACE_11(Expansion.Core),
    SPACE_12(Expansion.Core),
    SPACE_13(Expansion.Core),
    SPACE_14(Expansion.Core),
    SPACE_15(Expansion.Core),
    SPACE_16(Expansion.Core),
    SPACE_17(Expansion.Core),
    SPACE_18(Expansion.Core),
    SPACE_19(Expansion.Core),
    SPACE_20(Expansion.Core),
    SPACE_21(Expansion.Core),

    MISKATONIC_OUTPOST(Expansion.MoM),
    LAKE_CAMP(Expansion.MoM),
    FROZEN_WASTE(Expansion.MoM),
    CITY_OF_THE_ELDER_THINGS(Expansion.MoM),
    PLATEAU_OF_LENG(Expansion.MoM),
    SNOWY_MOUNTAINS(Expansion.MoM),

    CAIRO(Expansion.UtP),
    ALEXANDRIA(Expansion.UtP),
    NILE_RIVER(Expansion.UtP),
    SAHARA_DESERT(Expansion.UtP),
    BENT_PYRAMID(Expansion.UtP),
    TEL_EL_AMARNA(Expansion.UtP),

    CELEPHAIS(Expansion.TD),
    DYLATH_LEEN(Expansion.TD),
    THE_ENCHANTED_WOOD(Expansion.TD),
    THE_MOON(Expansion.TD),
    THE_UNDERWORLD(Expansion.TD),
    ULTHAR(Expansion.TD),
    UNKNOWN_KADATH(Expansion.TD)
}
